<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogMaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Лекарственные средства',
            'title_en' => 'Medicines',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 1,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Биологически активные добавки',
            'title_en' => 'Biologically active additives',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 2,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Пищевые продукты',
            'title_en' => 'Foodstuffs',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 3,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Сиропы',
            'title_en' => 'Syrups',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 4,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Гематогены',
            'title_en' => 'Hematogen',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 5,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Таблетки',
            'title_en' => 'Tablets',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 6,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Порошки и гранулы',
            'title_en' => 'Powders',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 7,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Капсулы',
            'title_en' => 'Capsules',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 8,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Прочие лекарственные средства',
            'title_en' => 'Other medicines',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 9,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Порошки и гранулы',
            'title_en' => 'Powders',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 10,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Капсулы',
            'title_en' => 'Capsules',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 11,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Прочие лекарственные средства',
            'title_en' => 'Other medicines',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 12,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Капсулы',
            'title_en' => 'Capsules',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 13,
        ]);
        DB::table('catalog_materials')->insert([
            'title_ru' => 'Прочие лекарственные средства',
            'title_en' => 'Other medicines',
            'short_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному, промежуточному контролю',
            'short_en' => 'Production is carried out on the basis of industry regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on the input',
            'text_ru' => 'Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.
                          Производство продукции осуществляется на основании промышленных регламентов, технологических инструкций, стандартных операционных процедур (СОП). На предприятии действует собственная служба обеспечения и контроля качества. Высококвалифицированный персонал выполняет работы по входному промежуточному контролю, а также контроль качества готовой продукции, контролирует хранение и реализацию. Процесс производства, обеспечения и контроль качества продукции ОАО "Экзон" гарантирует безопасность продукции, эффективность и полное соответствие техническим нормативным правовым актам и нормативным документам.',
            'text_en' => 'Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.
                          Production is carried out on the basis of industrial regulations, technological instructions, standard operating procedures (SOP). The company has its own service of quality assurance and control. Highly qualified personnel perform work on incoming intermediate control, as well as quality control of finished products, controls storage and sale. The process of production, supply and quality control of JSC "Exon" guarantees product safety, efficiency and full compliance with technical regulatory legal acts and regulatory documents.',
            'parent' => 14,
        ]);
    }
}
