<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert([
            'title_ru' => 'Международная специализированная выставка «Здравоохранение и Фармация EXPO-2017» в Ереване с 22 по 27 февраля1',
            'title_en' => 'International Specialized Exhibition "Healthcare and Pharmacy EXPO-2017" in Yerevan from February 22 to 271',
            'prev_text_ru' => 'Для акционеров ОАО "ЭКЗОН" об участии во внеочередном общем собрании акционеров1',
            'prev_text_en' => 'For shareholders of JSC "EKZON" on participation in the extraordinary general meeting of shareholders1',
            'text_ru' => 'Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.',
            'text_en' => 'Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.',
            'date' => date("Y-m-d H:i:s"),
            'default_img' => 'images/news/news-all__preview1.png',
            'share' => 1,
        ]);
        DB::table('news')->insert([
            'title_ru' => 'Международная специализированная выставка «Здравоохранение и Фармация EXPO-2017» в Ереване с 22 по 27 февраля2',
            'title_en' => 'International Specialized Exhibition "Healthcare and Pharmacy EXPO-2017" in Yerevan from February 22 to 272',
            'prev_text_ru' => 'Для акционеров ОАО "ЭКЗОН" об участии во внеочередном общем собрании акционеров2',
            'prev_text_en' => 'For shareholders of JSC "EKZON" on participation in the extraordinary general meeting of shareholders2',
            'text_ru' => 'Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.',
            'text_en' => 'Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.',
            'date' => date("Y-m-d H:i:s"),
            'default_img' => 'images/news/news-all__preview2.png',
            'share' => 0,
        ]);
        DB::table('news')->insert([
            'title_ru' => 'Международная специализированная выставка «Здравоохранение и Фармация EXPO-2017» в Ереване с 22 по 27 февраля3',
            'title_en' => 'International Specialized Exhibition "Healthcare and Pharmacy EXPO-2017" in Yerevan from February 22 to 273',
            'prev_text_ru' => 'Для акционеров ОАО "ЭКЗОН" об участии во внеочередном общем собрании акционеров3',
            'prev_text_en' => 'For shareholders of JSC "EKZON" on participation in the extraordinary general meeting of shareholders3',
            'text_ru' => 'Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.Сотрудники отдела маркетинга ОАО «Экзон» приняли участие в специализированной выставке «Здравоохранение и Фармация EXPO-2017», которая проходила 22-27 февраля в Ереване. В рамках участия в выставке была проведена дегустация продукции, а также были достигнуты договоренности о поставке гематогена в Республику Армения.',
            'text_en' => 'Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.Employees of marketing department of JSC "Exon" took part in the specialized exhibition "Healthcare and Pharmacy EXPO-2017", which was held on February 22-27 in Yerevan. Within the framework of participation in the exhibition, a tasting of products was conducted, and agreements were reached on the supply of hematogen to the Republic of Armenia.',
            'date' => date("Y-m-d H:i:s"),
            'default_img' => 'images/news/news-all__preview3.png',
            'share' => 0
        ]);
    }
}
